# NumPy Operations Notebook
This notebook demonstrates various basic and advanced operations in NumPy, a powerful numerical computing library in Python.

In [44]:
# Importing the NumPy library
import numpy as np

## 0. Why NumPy
Faster, more efficient, easier syntax, and allows operations over arrays.

Element-wise sum example

In [2]:
# Pure Python implementation
list1 = [i for i in range(10)]
list2 = [i for i in range(10)]

# Summing the two lists element-wise
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

# Print the first 10 elements of the result
print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [3]:
import numpy as np

# Numpy implementation
array1 = np.arange(10)
array2 = np.arange(10)

# Summing the arrays element-wise
result = array1 + array2

# Print the first 10 elements of the result
print(result)

[ 0  2  4  6  8 10 12 14 16 18]


Mean Square Error Example

In [4]:
# mean squared error in pure python
y_true = [1, 2, 3, 4, 5]
y_pred = [1.1, 2.1, 2.9, 4.2, 5.2]

# Calculate the mean squared error
error = sum([(yt - yp) ** 2 for yt, yp in zip(y_true, y_pred)]) / len(y_true)

print(error)

0.022000000000000037


In [5]:
# mean squared error in numpy
y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.1, 2.9, 4.2, 5.2])

# Calculate the mean squared error
error = np.mean((y_true - y_pred) ** 2)

print(error)

0.022000000000000037


## 1. Creating NumPy Arrays
There are several ways to create arrays in NumPy. Let's look at a few methods.

In [6]:
list_data = [1, 2, 3, 4, 5]
print("List:", list_data, type(list_data))

array_data = np.array(list_data)
print("Array:", array_data, type(array_data))

List: [1, 2, 3, 4, 5] <class 'list'>
Array: [1 2 3 4 5] <class 'numpy.ndarray'>


### Special Array Creation Functions
NumPy also provides functions for creating arrays with specific values, such as zeros, ones, and random numbers.

In [7]:
array_1d = np.array([1, 2, 3, 4, 5])  # 1D array

array_zeros = np.zeros(5)  # array filled with zeros

array_ones = np.ones(5)  # array filled with ones

array_sevens = np.full(5, 7)  # array filled with sevens

print("1D array:", array_1d)
print("Array filled with zeros:", array_zeros)
print("Array filled with ones:", array_ones)
print("Array filled with sevens:", array_sevens)

1D array: [1 2 3 4 5]
Array filled with zeros: [0. 0. 0. 0. 0.]
Array filled with ones: [1. 1. 1. 1. 1.]
Array filled with sevens: [7 7 7 7 7]


#### Arrays with Ranges
NumPy provides two important functions for creating sequences of numbers: `arange()` and `linspace()`.

In [8]:
array_range = np.arange(0, 10, 1)  # numbers from 0 to 10 with step 1

array_linspace = np.linspace(0, 10, 5) # 5 linearly spaced numbers between 0 and 10

array_random = np.random.rand(5)  # 5 random numbers between 0 and 1

print("Range:", array_range)
print("Linearly spaced:", array_linspace)
print("Random numbers:", array_random)

Range: [0 1 2 3 4 5 6 7 8 9]
Linearly spaced: [ 0.   2.5  5.   7.5 10. ]
Random numbers: [0.86149572 0.22874223 0.12036243 0.39113787 0.8313585 ]


## 2. Checking Dimensions
Arrays can have multiple sizes (number of elements) dimensions (shape). 
For example, a 1D array is a vector, a 2D array is a matrix, and a 3D array is a tensor. 

In [9]:
# showing the dimensions of an array
array = np.array([7, 2, 9, 10])
print("1D array:\n", array)
print("Number of elements in the array:", array.size)
print("Dimensions of the array:", array.ndim)
print("Shape of the array:", array.shape)

1D array:
 [ 7  2  9 10]
Number of elements in the array: 4
Dimensions of the array: 1
Shape of the array: (4,)


In [10]:
array = np.array([[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]])
print("2D array:\n", array)
print("Number of elements in the array:", array.size)
print("Dimensions of the array:", array.ndim)
print("Shape of the array:", array.shape)

2D array:
 [[5.2 3.  4.5]
 [9.1 0.1 0.3]]
Number of elements in the array: 6
Dimensions of the array: 2
Shape of the array: (2, 3)


In [11]:
# 3D array
array = np.array([[[1, 2], [3, 4], [5, 6]], 
                  [[7, 8], [9, 10], [11, 12]], 
                  [[13, 14], [15, 16], [17, 18]], 
                  [[19, 20], [21, 22], [23, 24]]
                  ])
print("3D array:\n", array)
print("Number of elements in the array:", array.size)
print("Dimensions of the array:", array.ndim)
print("Shape of the array:", array.shape)

3D array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
Number of elements in the array: 24
Dimensions of the array: 3
Shape of the array: (4, 3, 2)


## 3. Array Indexing and Slicing
You can access individual elements, or a range of elements (slice) in an array using standard Python indexing.

In [12]:
# accessing index of each element
array_1d = np.array([1, 2, 3, 4, 5])

print("First element:", array_1d[0])
print("Second element:", array_1d[1])
print("Last element:", array_1d[-1])

First element: 1
Second element: 2
Last element: 5


#### Indexing in 2D Arrays
In 2D arrays, you can access elements using row and column indices.

In [13]:
# 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

print("First row and second column:", array_2d[0, 1])
print("Last row and first column:", array_2d[-1, 0])

First row and second column: 2
Last row and first column: 4


### Array Slicing
Slicing is used to get a portion of the array.

In [14]:
# examples of array slicing in 1D array
array = np.array([1, 2, 3, 4, 5])

# slice from index 1 to 3 (exclusive)
print("array[1:3] ->", array[1:3])

# slice from index 0 to 4 (exclusive)
print("array[:4] ->", array[:4])

array[1:3] -> [2 3]
array[:4] -> [1 2 3 4]


In [15]:
# examples of array slicing in 1D array
array = np.array([1, 2, 3, 4, 5])

# slice from index 1 to the end
print("array[1:] ->", array[1:])

# slice from the beginning to the end
print("array[:] ->", array[:])

# slice with a step of 2
print("array[::2] ->", array[::2])

array[1:] -> [2 3 4 5]
array[:] -> [1 2 3 4 5]
array[::2] -> [1 3 5]


Slicing a 2D Array

In [16]:
# examples of 6 by 6 array starting from 0
array = np.arange(36).reshape(6, 6)

print("Original array:")
print(array)

array_slice = array[0,3:5]  # first row, 4th and 5th columns
print("\nSlice array:")
print(array_slice)

array_slice = array[4:,4:]  # last two rows, last two columns
print("\nSlice array:")
print(array_slice)

array_slice = array[:,2]  # all rows, 3rd column
print("\nSlice array:")
print(array_slice)

array_slice = array[2::2,::2]  # every other row starting from the 3rd row, every other column
print("\nSlice array:")
print(array_slice)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Slice array:
[3 4]

Slice array:
[[28 29]
 [34 35]]

Slice array:
[ 2  8 14 20 26 32]

Slice array:
[[12 14 16]
 [24 26 28]]


### Exercise: Indexing and Slicing

The aim is given guess before running what the result should be for each operation.

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# What is the value of arr_1d[2]?
# uncomment the next line to get the answer
# print(arr_1d[2])

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# What is the value of arr_1d[-1]?
# uncomment the next line to get the answer
# print(arr_1d[-1])

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# What is the value of arr_1d[1:4]?
# uncomment the next line to get the answer
# print(arr_1d[1:4])

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# What is the value of arr_1d[::2]?
# uncomment the next line to get the answer
# print(arr_1d[::2])

Now for the 2D case

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# What is the value of arr_2d[1, 2]?
# uncomment the next line to get the answer
# print(arr_2d[1, 2])

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# What is the value of arr_2d[1, 2]
# uncomment the next line to get the answer
# print(arr_2d[1, 2])

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# What is the value of arr_2d[:, 0]
# uncomment the next line to get the answer
# print(arr_2d[:, 0])

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# What is the value of arr_2d[0:2, 1:3]
# uncomment the next line to get the answer
# print(arr_2d[0:2, 1:3])

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# What is the value of arr_2d[::2, ::2]
# uncomment the next line to get the answer
# print(arr_2d[::2, ::2])

## Data Types
Numpy supports various data types such as int, float, str, bool, etc.

The default data type is inferred from the input data

In [58]:
# examples of various data types
array = np.array([1, 2, 3, 4, 5])
print("Default data type:", array.dtype)

array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print("Default data type:", array.dtype)

array = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print("Custom data type:", array.dtype)

array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Custom data type:", array.dtype)

array = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print("Custom data type:", array.dtype)

# str
array = np.array(["apple", "banana", "cherry"])
print("Default data type:", array.dtype)

# bool
array = np.array([True, False, True])
print("Default data type:", array.dtype)

Default data type: int64
Default data type: float64
Custom data type: float64
Custom data type: int32
Custom data type: int16
Default data type: <U6
Default data type: bool


Conversion to other data types is possilb eusing astype() function.

In [51]:
# converting data types
array = np.array([1, 2, 3, 4, 5])
print("Original data:", array, array.dtype)

# converting from int to float
array = array.astype(np.float64)
print("New data:", array, array.dtype)

Original data type: [1 2 3 4 5] int64
New data type: [1. 2. 3. 4. 5.] float64


In [53]:
# converting from float to int
array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print("Original data:", array, array.dtype)

array = array.astype(np.int32)
print("New data:", array, array.dtype)

Original data: [1.1 2.2 3.3 4.4 5.5] float64
New data: [1 2 3 4 5] int32


In [54]:
# converting from int to str
array = np.array([1, 2, 3, 4, 5])
print("Original data:", array, array.dtype)

array = array.astype(str)
print("New data:", array, array.dtype)

Original data: [1 2 3 4 5] int64
New data: ['1' '2' '3' '4' '5'] <U21


In [56]:
# int summing with float
array_int = np.array([1, 2, 3, 4, 5])
array_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

result = array_int + array_float
print("Result:", result, result.dtype)

Result: [ 2.1  4.2  6.3  8.4 10.5] float64


Not all types are interoperable with each other.

In [57]:
# int summing with str
array_int = np.array([1, 2, 3, 4, 5])
array_str = np.array(["1", "2", "3", "4", "5"])

result = array_int + array_str  # this will result in an error!
print("Result:", result, result.dtype)   

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

## 4. Basic Operations on Arrays
NumPy arrays support element-wise operations, which means you can perform arithmetic operations directly on arrays.

In [17]:
# Element-wise operations
arr = np.array([1, 2, 3, 4])
arr_sum = arr + 10  # Add 10 to each element
arr_square = arr ** 2  # Square each element

print("Original Array:\n", arr)
print("\nArray after adding 10:\n", arr_sum)
print("\nArray after squaring:\n", arr_square)

Original Array:
 [1 2 3 4]

Array after adding 10:
 [11 12 13 14]

Array after squaring:
 [ 1  4  9 16]


Operations involving multiple 1D-arrays

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

addition = arr1 + arr2
subtraction = arr1 - arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nAddition:", addition)
print("Subtraction:", subtraction)

Array 1: [1 2 3]
Array 2: [4 5 6]

Addition: [5 7 9]
Subtraction: [-3 -3 -3]


In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mult = arr1 * arr2
division = arr1 / arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Mult:", mult)
print("Division:", division)

Array 1: [1 2 3]
Array 2: [4 5 6]
Mult: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Operations involing 2D-arrays

In [20]:
# element-wise operations with 2D arrays
arr = np.array([[1, 2], [3, 4]])
arr_sum = arr + 10  # Add 10 to each element

print("Original Array:\n", arr)
print("\nArray after adding 10:\n", arr_sum)

Original Array:
 [[1 2]
 [3 4]]

Array after adding 10:
 [[11 12]
 [13 14]]


In [21]:
# element-wise operations with 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

addition = arr1 + arr2
subtraction = arr1 - arr2

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("\nAddition:\n", addition)
print("Subtraction:\n", subtraction)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [22]:
# element-wise operations with 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

mult = arr1 * arr2
division = arr1 / arr2

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("\nMult:\n", mult)
print("Division:\n", division)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Mult:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 5. Aggregation Functions
NumPy provides various functions to compute aggregate values, such as `sum()`, `mean()`, `max()`, `min()`.

In [23]:
# Aggregation functions
arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(arr)  # Sum of all elements
column_sum = np.sum(arr, axis=0)  # Sum along columns
min_value = np.min(arr)  # Minimum value in the array
arg_min = np.argmin(arr)  # Index of minimum value
max_value = np.max(arr)  # Maximum value in the array
arg_max = np.argmax(arr)  # Index of maximum value

print("Array:\n", arr)
print("Total sum of array elements:", total_sum)
print("Column-wise sum:", column_sum)
print("Minimum value in array:", min_value)
print("Index of minimum value:", arg_min)
print("Maximum value in array:", max_value)
print("Index of maximum value:", arg_max)

Array:
 [[1 2 3]
 [4 5 6]]
Total sum of array elements: 21
Column-wise sum: [5 7 9]
Minimum value in array: 1
Index of minimum value: 0
Maximum value in array: 6
Index of maximum value: 5


In [24]:
# Aggregation functions
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean_value = np.mean(arr)  # Mean of all elements
median_value = np.median(arr)  # Median of all elements
mean = np.mean(arr, axis=0)  # Mean along columns
std_value = np.std(arr)  # Standard deviation of all elements

print("Array:\n", arr)
print("Mean of array elements:", mean_value)
print("Mean along columns:", mean)
print("Median of array elements:", median_value)
print("Standard deviation of array elements:", round(std_value, 3))

Array:
 [[1 2 3]
 [4 5 6]]
Mean of array elements: 3.5
Mean along columns: [2.5 3.5 4.5]
Median of array elements: 3.5
Standard deviation of array elements: 1.708


## 6. Boolean Masking and Conditional Selection
You can apply conditions to arrays and use them to select specific elements using boolean masks.

In [25]:
# Boolean masking and conditional selection
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30  # Create a boolean mask where values are greater than 30
selected_elements = arr[mask]  # Use the mask to select elements

print("Original array:\n", arr)
print("\nBoolean mask (arr > 30):\n", mask)
print("\nSelected elements (arr[mask]):\n", selected_elements)

Original array:
 [10 20 30 40 50]

Boolean mask (arr > 30):
 [False False False  True  True]

Selected elements (arr[mask]):
 [40 50]


In [26]:
# using np.where() to select elements based on condition
arr = np.array([10, 20, 30, 40, 50])
selected_elements = np.where(arr > 30)  # Select elements where value > 30

print("Original array:\n", arr)
print("\nSelected elements (arr > 30):\n", selected_elements)
print("\nSelected elements:\n", arr[selected_elements])

Original array:
 [10 20 30 40 50]

Selected elements (arr > 30):
 (array([3, 4]),)

Selected elements:
 [40 50]


Using multiple conditions for filtering 

In [27]:
# chaining multiple conditions
arr = np.array([10, 20, 30, 40, 50])
# Select elements where 20 < value < 50
selected_elements = arr[(arr > 20) & (arr < 50)]

print("Original array:\n", arr)
print("\nSelected elements (20 < arr < 50):\n", selected_elements)

# logical or operation
# Select elements where value < 20 or value > 40
selected_elements = arr[(arr < 20) | (arr > 40)]
print("\nSelected elements (arr < 20 or arr > 40):\n", selected_elements)

Original array:
 [10 20 30 40 50]

Selected elements (20 < arr < 50):
 [30 40]

Selected elements (arr < 20 or arr > 40):
 [10 50]


## 7. Sorting
Sorting is used to put elements in a certain order.

In [28]:
# example of sorting
array = np.array([3, 1, 2, 4, 5])

# Sort the array
sorted_array = np.sort(array)
print("Original array:", array)
print("Sorted array:", sorted_array)

Original array: [3 1 2 4 5]
Sorted array: [1 2 3 4 5]


In 2D arrays it sorts by the index passed.

In [29]:
# example of sorting a 2D array
array = np.array([[3, 4, 5], [1, 3, 2]])

# Sort the array along the rows
sorted_array_rows = np.sort(array, axis=0)
print("Original array:\n", array)
print("Sorted array along the rows:\n", sorted_array_rows)

# Sort the array along the columns
sorted_array_columns = np.sort(array, axis=1)
print("Sorted array along the columns:\n", sorted_array_columns)

Original array:
 [[3 4 5]
 [1 3 2]]
Sorted array along the rows:
 [[1 3 2]
 [3 4 5]]
Sorted array along the columns:
 [[3 4 5]
 [1 2 3]]


In [30]:
# argsort() function
array = np.array([3, 1, 2, 4, 5])

# Get the indices that would sort the array
indices = np.argsort(array)
print("Original array:", array)
print("Indices of sorted array:", indices)

# sort using the indices
sorted_array = array[indices]
print("Sorted array:", sorted_array)

Original array: [3 1 2 4 5]
Indices of sorted array: [1 2 0 3 4]
Sorted array: [1 2 3 4 5]


## Exercise - The Students
You have the data of a class of students in two arrays: one for their ages and one for their heights. Use NumPy to answer the following questions and perform some filtering operations.

**Tasks:**
1. **Average Age and Height:** Calculate the average (mean) age and height of the students.
2. **Filter by Height:** Find the students who are taller than 165 cm and print their ages.
3. **Standard Deviation:** Calculate the standard deviation of the ages and heights.
4. **Students within Range:** Find the students whose ages are between 15 and 17 (inclusive) and their heights.
5. **Tallest Student:** Find the age and height of the tallest student.
6. **Sort by Height:** Sort the students by their heights in ascending order and print their corresponding 
ages.

**Hints:**

Use the functions presented earlier such as: mean, argmax std and sort. 

Also use operations such multiple condition filtering, and selection through masks.

In [60]:
# Student Data
ages = np.array([15, 16, 14, 15, 16, 17, 15, 14, 16, 15])
heights = np.array([160, 165, 158, 162, 170, 175, 161, 159, 168, 163])

In [65]:
# 1: Calculate the mean age and height
pass

Mean age: 15.3
Mean height: 164.1


In [66]:
# 2. Find the students who are taller than 165 cm and print their ages.
pass

Ages of students taller than 165 cm: [16 17 16]


In [67]:
# 3. Calculate the standard deviation of the ages and heights.
pass

Standard deviation of ages: 0.9
Standard deviation of heights: 5.15


In [88]:
# 4. Find students aged between 15 and 17 and their heights
pass

In [69]:
# 5. Find the age and height of the tallest student
pass

Tallest Student Age: 17
Tallest Student Height: 175


In [70]:
# 6. Sort the students by their heights and print their corresponding ages
pass

Heights in ascending order: [158 159 160 161 162 163 165 168 170 175]
Corresponding ages in ascending height order: [14 14 15 15 15 15 16 16 16 17]


**New task 7:**

Calculate the BMI (Body Mass Index) for each student given the new information about their weights.

BMI=(weight in kg/(height in meters/100)^2)

And then print the weights, heights, and ages that are not in the regular range of 18.5 and 24.9.

In [86]:
weights = np.array([50, 55, 45, 48, 60, 72, 51, 47, 65, 52])

# calculate the BMI of each student -> element-wise operations
pass

# Find students with BMI less than 18.5 or greater than 24.9 -> filtering with multiple conditions
pass

# weights, heights, and ages of students in regular range -> filtering using a mask
pass

BMI of students: [19.53 20.2  18.03 18.29 20.76 23.51 19.68 18.59 23.03 19.57]
BMI mask: [False False  True  True False False False False False False]
Weights of students with BMI less than 18.5 or greater than 24.9: [45 48]
Heights of students with BMI less than 18.5 or greater than 24.9: [158 162]
Ages of students with BMI less than 18.5 or greater than 24.9: [14 15]


## 7. Reshaping and Transposing Arrays
You can change the shape of an array using the `reshape()` function, and transpose arrays using the `T` attribute.

In [31]:
# flattening a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_arr = arr2d.flatten()

print("Original 2D array:\n", arr2d)
print("\nFlattened array:\n", flattened_arr)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened array:
 [1 2 3 4 5 6 7 8 9]


In [32]:
# Reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape(3, 2)  # Reshape 2x3 array to 3x2

print("Original array:\n", arr)
print("\nReshaped array (3x2):\n", reshaped)

Original array:
 [[1 2 3]
 [4 5 6]]

Reshaped array (3x2):
 [[1 2]
 [3 4]
 [5 6]]


In [33]:
# Transposing arrays
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
transposed = arr.T  # Transpose the array

print("Original array:\n", arr)
print("Shape of original array:", arr.shape)
print("\nTransposed array:\n", transposed)
print("Shape of transposed array:", transposed.shape)

# other way to transpose
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

arr_transpose = np.transpose(arr)


Original array:
 [[1 2 3]
 [4 5 6]]
Shape of original array: (2, 3)

Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Shape of transposed array: (3, 2)


## 8. Broadcasting
Broadcasting allows you to perform element-wise operations on arrays of different shapes.

In [34]:
# Broadcasting example
arr = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
broadcasted_sum = arr + vector  # Adds vector to each row of arr

print("Original array:\n", arr)
print("\nVector:\n", vector)
print("\nArray after broadcasting:\n", broadcasted_sum)

Original array:
 [[1 2 3]
 [4 5 6]]

Vector:
 [1 2 3]

Array after broadcasting:
 [[2 4 6]
 [5 7 9]]


## 9. Stacking and Concatenating Arrays
You can stack arrays vertically (`vstack()`) or horizontally (`hstack()`), as well as concatenate them using `concatenate()`.

In [35]:
# Stacking and concatenating arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vertical_stack = np.vstack((arr1, arr2))  # Stack arrays vertically

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nVertically stacked:\n", vertical_stack)

Array 1:
 [1 2 3]

Array 2:
 [4 5 6]

Vertically stacked:
 [[1 2 3]
 [4 5 6]]


In [36]:
# Stacking and concatenating arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
horizontal_stack = np.hstack((arr1, arr2))  # Stack arrays horizontally

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nHorizontally stacked:\n", horizontal_stack)

Array 1:
 [1 2 3]

Array 2:
 [4 5 6]

Horizontally stacked:
 [1 2 3 4 5 6]


## 10. Dot Product

In [37]:
# dot product of two 1d arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nDot product:", dot_product)

Array 1: [1 2 3]
Array 2: [4 5 6]

Dot product: 32


In [38]:
# numpy dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(arr1, arr2)

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nDot product of the two arrays:\n", dot_product)

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Dot product of the two arrays:
 [[19 22]
 [43 50]]


Dot product of matrices is not cummutative

In [39]:
# numpy dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(arr2, arr1)

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nDot product of the two arrays:\n", dot_product)

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Dot product of the two arrays:
 [[23 34]
 [31 46]]


## 11. Handling Missing Values
There are instances where there might be values missing.

In computing, NaN (Not a Number) is a value used to represent a numeric value that is undefined or unrepresentable.

In [40]:
# handling nans
arr = np.array([1, np.nan, 3, 4])
print("Array with NaN:\n", arr)

Array with NaN:
 [ 1. nan  3.  4.]


In [41]:
# handling nans
arr = np.array([1, np.nan, 3, 4])
nan_index = np.isnan(arr)  # Find indices of NaN values

print("Array with NaN:\n", arr)
print("\nIndices of NaN values:", nan_index)

# handling nans
arr = np.array([1, np.nan, 3, 4])
arr[nan_index] = 0  # Replace NaN values with 0

print("Array with NaN replaced by 0:\n", arr)

Array with NaN:
 [ 1. nan  3.  4.]

Indices of NaN values: [False  True False False]
Array with NaN replaced by 0:
 [1. 0. 3. 4.]


In [42]:
# handling nans
arr = np.array([1, np.nan, 3, 4])

arr_filled = np.nan_to_num(arr)  # Replace NaN values with 0

print("Array with NaN:\n", arr)

print("\nArray with NaN replaced by 0:\n", arr_filled)

Array with NaN:
 [ 1. nan  3.  4.]

Array with NaN replaced by 0:
 [1. 0. 3. 4.]


In [43]:
# handling nans
arr = np.array([1, np.nan, 3, 4])

arr_without_nan = arr[~np.isnan(arr)]  # Remove NaN values from array

print("Array with NaN:\n", arr)

print("\nArray without NaN values:", arr_without_nan)

Array with NaN:
 [ 1. nan  3.  4.]

Array without NaN values: [1. 3. 4.]


## 12. Conclusion
This notebook demonstrated a variety of NumPy operations.

NumPy's powerful array handling and vectorized operations make it an essential library for numerical computing in Python.